### ISSUE TITLE
How to generate senzing dnb_mappers.json file using dnb_mappers.py to upload it to Postgresql DB?

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/mapper-dnb#6]
Hi Team,

We are in need of a clarification regarding DnB JSON data creation.

We came to know senzing dnb_mappers.py couldn't able to return the format we expect. So we are trying to prepare a new script to create a json file to upload it to the postgres DB.

We've no idea on what dnb_mappers.py script doing, what it is mapping or where is it referring to map the data from?

Kindly assist us to get clarified asap.

Thanks.

**Comment by jbutcher21** [comment]
So it converts these D&B formats ...
- Companies and their principles (CMPCVF) json format
- Global contacts (GCA) tab delimited csv format
- Ultimate beneficial owners (UBO) tab delinited csv format

What format do you have if not one of those?

**Comment by jbutcher21** [comment]
@SaravananKalimuthu21 ...
So it converts these D&B formats ...
- Companies and their principles (CMPCVF) json format
- Global contacts (GCA) tab delimited csv format
- Ultimate beneficial owners (UBO) tab delinited csv format
What format do you have if not one of those?

**Comment by SaravananKalimuthu21** [comment]
Hi Jeff,

We have two files with the following fields and those are to be used to create .json file and to be uploaded into our Postgres db.

**Dnb_cayman_corporate_data.csv**
Company Name	Tradestyle	D-U-N-S® Number	Address Line 1	Address Line 2	Address Line 3	City	State Or Province	Postal Code	Country/Region	Phone	Fax	URL	Revenue (USD)	Pre Tax Profit (USD)	Assets (USD)	Liabilities (USD)	Employees (Single Site)	Employees (All Sites)	Business Description	Ownership Type	Entity Type	Is Headquarters	Ticker	Parent Company	Parent Country/Region	Ultimate Parent Company	Ultimate Parent Country/Region	D&B Hoovers Industry	US 8-Digit SIC Code	US 8-Digit SIC Description	US SIC 1987 Code	US SIC 1987 Description	NAICS 2017 Code	NAICS 2017 Description	UK SIC 2007 Code	UK SIC 2007 Description	ISIC Rev 4 Code	ISIC Rev 4 Description	NACE Rev 2 Code	NACE Rev 2 Description	ANZSIC 2006 Code	ANZSIC 2006 Description	TPS Flag	Key ID	Source	Direct Marketing Status

**DNB_Executives_Cayman_islands.xlsx**
First Name	Last Name	Title	Company Name	Tradestyle	D-U-N-S® Number	Contact Level	Job Function	Email	Direct Phone	Address Line 1	Address Line 2	Address Line 3	City	State Or Province	Postal Code	Country/Region	Phone	Fax	URL	Revenue (USD)	Pre Tax Profit (USD)	Assets (USD)	Liabilities (USD)	Employees (Single Site)	Employees (All Sites)	Business Description	Ownership Type	Entity Type	Is Headquarters	Ticker	Parent Company	Parent Country/Region	Ultimate Parent Company	Ultimate Parent Country/Region	D&B Hoovers Industry	US 8-Digit SIC Code	US 8-Digit SIC Description	US SIC 1987 Code	US SIC 1987 Description	NAICS 2017 Code	NAICS 2017 Description	UK SIC 2007 Code	UK SIC 2007 Description	ISIC Rev 4 Code	ISIC Rev 4 Description	NACE Rev 2 Code	NACE Rev 2 Description	ANZSIC 2006 Code	ANZSIC 2006 Description	TPS Flag	Key ID	Dedup ID	Source	Direct Marketing Status

We converted .csv and .xlsx files into .txt by just renaming them and passed it to the following command and decide to run **Dnb_cayman_corporate_data.csv** using **CMPCVF** format and **DNB_Executives_Cayman_islands.xlsx** using **GCA** format.

$ python3 dnb_mapper.py -f CMPCVF -i "./input/Dnb_cayman_corporate_data.txt" -o ./output -l cmpcvf_stats.json

$ python3 dnb_mapper.py -f GCA -i "./input/DNB_Executives_Cayman_islands.txt" -o ./output -l gca_stats.json

We faced the issue which is mentioned in the image attached.
![DNB_Executives_Cayman_islands_GCA](https://user-images.githubusercontent.com/48215082/75980504-9ad13380-5f08-11ea-908b-0a97490e808d.png)
![Dnb_cayman_corporate_data_CMPCVF](https://user-images.githubusercontent.com/48215082/75980508-9c026080-5f08-11ea-8ba0-20f0f32732e1.png)

Is there any way to run .csv files directly in the command or have to convert it to .txt files before running?

We need clarification on how to generate .json file with our input files.

Thanks.

**Comment by jbutcher21** [comment]
Ok so those cayman island files do not match any of the DNB formats the GitHub DNB mapper.  There is now a csv mapper that can map any csv file that you should use. 
https://github.com/Senzing/mapper-csv
However, in the interest of time, please send me those files and I will see what I can do.

**Comment by jbutcher21** [comment]
Hi Saravanan,

Did you still need any help with those Cayman Island D&B files?   If so, send them to me and I will help you get them mapped.

Jeff Butcher
Senzing, Chief Architect
jbutcher@senzing.com<mailto:jbutcher@senzing.com>
(702) 205-8424

Follow Senzing on Website<http://www.senzing.com/> | Twitter<https://twitter.com/senzing> | LinkedIn<https://www.linkedin.com/company/senzing-inc/> | Facebook<https://www.facebook.com/senzinginc/>
If you are not an intended recipient of confidential and privileged information in this email, please delete it, notify us immediately at postmaster@senzing.com<mailto:postmaster@senzing.com>, and do not use or disseminate such information.

**Comment by SaravananKalimuthu21** [comment]
Thanks Jeff,

We were discussing with the Consilienz team, and they are Analysing the dnb data and will get back to us.

We will update you once we get a next level clarification from them.

**Comment by jbutcher21** [comment]
Ok, I'm going to close this issue for now then.   Ready to help when needed!
